name: CI and CD for safebrowse

# on for starting the workflow on push and pull requet in main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# after triggering workflow first job is to run the tester
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test 

  # if tests are succesfull the next job is to deploy the 
  # changes to render.com through API request made with curl
  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Render
        run: |
          curl -fsSL https://render.com/deploy/${{ secrets.RENDER_API_TOKEN }} -X POST
