name: CI and CD for safebrowse

# Trigger the workflow on push and pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  # Runs Jest tests

  # Job to deploy to Render if tests pass
  deploy:
    runs-on: ubuntu-latest
    needs: test  # will run only if the 'test' job succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.6.1'

      - name: Install dependencies
        run: npm install

      - name: Deploy to Render
        run: |
          curl -fsSL https://render.com/deploy/${{ secrets.RENDER_API_TOKEN }} -X POST
